//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controller.LocalExampleSvc {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wishuok.com/", ConfigurationName="LocalExampleSvc.ExampleSvcSoap")]
    public interface ExampleSvcSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wishuok.com/GetDataTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDataTable(string colName, int colCnt, int rowCnt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExampleSvcSoapChannel : Controller.LocalExampleSvc.ExampleSvcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExampleSvcSoapClient : System.ServiceModel.ClientBase<Controller.LocalExampleSvc.ExampleSvcSoap>, Controller.LocalExampleSvc.ExampleSvcSoap {
        
        public ExampleSvcSoapClient() {
        }
        
        public ExampleSvcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExampleSvcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExampleSvcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExampleSvcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetDataTable(string colName, int colCnt, int rowCnt) {
            return base.Channel.GetDataTable(colName, colCnt, rowCnt);
        }
    }
}
